### ISSUE TITLE
Rename "location" to "project" to follow GRASS GIS

### ISSUE THREAD

**Issue by mmacata** [actinia-org/actinia-api#22]
Should be backward compatible in transition phase. Plan of GRASS GIS:
> Main transition will happen for 8.4 and is designed to be backward
> compatible until the 9.0 release.

See here for more details
https://lists.osgeo.org/pipermail/grass-user/2023-December/083478.html

**Comment by ninsbl** [comment]
See: https://github.com/orgs/OSGeo/projects/2/views/1 for renaming-progress in GRASS GIS.

Here is a first draft PR that adresses the first changes in GRASS GIS made so far: #24

**Comment by anikaweinmann** [comment]
Changed text in actinia-api
